services:
  web:
    container_name: health_care
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
    networks:
      - local
    env_file:
      - .env
    volumes:
      - .:/app
networks:
  local:
    driver: bridge
