version: '3'
services:
    web:
        container_name: health_care
        image: sherlockvufullsnack/health_care-api:latest
        ports:
            - '5005:5005'
        depends_on:
            - redis
            - postgresql-master
        networks:
            - app-network
        environment:
            - ENV=${ENV}
            - POSTGRES_URL_MASTER=${POSTGRES_URL_MASTER}
            - POSTGRES_URL_SLAVE=${POSTGRES_URL_SLAVE}
            - BROKER_URL=${BROKER_URL}
            - REDIS_URL=${REDIS_URL}
            - PORT=${PORT}
            - ACCESS_TOKEN=${ACCESS_TOKEN}
            - REFRESH_TOKEN=${REFRESH_TOKEN}
            - ALGORITHM=${ALGORITHM}
            - PREFIX_URL=${PREFIX_URL}
            - ACCOUNT_SID=${ACCOUNT_SID}
            - AUTH_TOKEN=${AUTH_TOKEN}
        volumes:
            - .:/app
    redis:
        container_name: redis-lung
        image: redis:alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --loglevel warning
        volumes:
            - ./docker-volumes/cache:/data
        networks:
            - app-network

    redis-commander:
        container_name: redis-commander-lung
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        ports:
            - '8081:8081'
        environment:
            - REDIS_HOSTS=local:redis:6379
        networks:
            - app-network

    postgresql-master:
        container_name: postgresql-master-lung-container
        image: 'docker.io/bitnami/postgresql:11-debian-10'
        ports:
            - '5400:5432'
        volumes:
            - 'postgresql_master_data:/bitnami/postgresql'
        environment:
            - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
            - POSTGRESQL_LOG_HOSTNAME=true
            - POSTGRESQL_REPLICATION_MODE=master
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_password
            - POSTGRESQL_USERNAME=admin
            - POSTGRESQL_PASSWORD=admin
            - POSTGRESQL_DATABASE=health_care
            - ALLOW_EMPTY_PASSWORD=no
        networks:
            - app-network

    postgresql-slave:
        container_name: postgresql-slave-lung-container
        image: 'docker.io/bitnami/postgresql:11-debian-10'
        ports:
            - '5401:5432'
        depends_on:
            - postgresql-master
        environment:
            - POSTGRESQL_USERNAME=postgres
            - POSTGRESQL_PASSWORD=postgres
            - POSTGRESQL_DATABASE=health_care
            - POSTGRESQL_MASTER_HOST=postgresql-master
            - POSTGRESQL_PGAUDIT_LOG=READ
            - POSTGRESQL_LOG_HOSTNAME=true
            - POSTGRESQL_REPLICATION_MODE=slave
            - POSTGRESQL_REPLICATION_USER=repl_user
            - POSTGRESQL_REPLICATION_PASSWORD=repl_password
            - POSTGRESQL_MASTER_PORT_NUMBER=5432
        networks:
            - app-network

    adminer:
        container_name: adminer-lung
        image: adminer
        restart: always
        ports:
            - '9999:8080'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgresql_master_data:
        driver: local
