services:
    bot_chat:
        container_name: bot_chat_service
        image: sherlockvufullsnack/health_care_bot-api:1.0
        restart: always
        ports:
            - '6000:8080'
    redis:
        container_name: redis_health_care
        image: redis:alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --loglevel warning
        networks:
            - local
    postgres:
        container_name: postgres_health_care
        image: postgres:13.15
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "health_care"
            PGDATA: "/data"
        volumes:
        - ./postgres/config:/config/
        networks:
            - local
networks:
    local:
        driver: bridge
