"""update default 3 value for 3 field

Revision ID: 2e8040defe4d
Revises: 1127723b84f2
Create Date: 2024-09-18 00:33:32.982597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8040defe4d'
down_revision: Union[str, None] = '1127723b84f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_record', sa.Column('main_defense', sa.Text(), nullable=False))
    op.add_column('medical_record', sa.Column('secondary_diseases', sa.Text(), nullable=False))
    op.add_column('medical_record', sa.Column('treatment_results', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_record', 'treatment_results')
    op.drop_column('medical_record', 'secondary_diseases')
    op.drop_column('medical_record', 'main_defense')
    # ### end Alembic commands ###
