"""create table dailey

Revision ID: 30d30cac42dc
Revises: eb50dccf9282
Create Date: 2024-09-25 10:11:15.870487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30d30cac42dc'
down_revision: Union[str, None] = 'eb50dccf9282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_health_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('assessment', sa.String(), nullable=False),
    sa.Column('describe_health', sa.Text(), nullable=True),
    sa.Column('link_image_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_health_check')
    # ### end Alembic commands ###
