"""add field name conversation

Revision ID: 392e2cb45432
Revises: 9dbe3d0a3cd8
Create Date: 2024-10-11 00:55:35.770713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392e2cb45432'
down_revision: Union[str, None] = '9dbe3d0a3cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'name')
    # ### end Alembic commands ###
