"""add field view  to viewedin table 

Revision ID: 3f5e9d309b93
Revises: bdcfe4ee5e97
Create Date: 2024-10-13 16:23:48.646191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5e9d309b93'
down_revision: Union[str, None] = 'bdcfe4ee5e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('viewed', sa.Integer(), nullable=False))
    op.drop_column('post', 'view')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('view', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('post', 'viewed')
    # ### end Alembic commands ###
