"""add field rep_id

Revision ID: 4242073f236d
Revises: 81a64914a453
Create Date: 2024-10-19 00:17:48.228799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4242073f236d'
down_revision: Union[str, None] = '81a64914a453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rep_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['rep_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'rep_id')
    # ### end Alembic commands ###
