"""remove message model and conversation

Revision ID: 592c68fe4fe1
Revises: ffd5ee99e183
Create Date: 2024-10-09 23:05:40.915455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '592c68fe4fe1'
down_revision: Union[str, None] = 'ffd5ee99e183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conversation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name='conversation_appointment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='conversation_pkey'),
    sa.UniqueConstraint('appointment_id', name='conversation_appointment_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reply_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='message_conversation_id_fkey'),
    sa.ForeignKeyConstraint(['reply_id'], ['message.id'], name='message_reply_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    # ### end Alembic commands ###
