"""update table conversation and message

Revision ID: 5b95133fe585
Revises: cf1b027d1a0f
Create Date: 2024-10-09 21:31:09.053846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b95133fe585"
down_revision: Union[str, None] = "cf1b027d1a0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_user")
    op.add_column(
        "conversation", sa.Column("appointment_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "conversation", ["appointment_id"])
    op.create_foreign_key(
        None, "conversation", "appointment", ["appointment_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.drop_constraint(None, "conversation", type_="unique")
    op.drop_column("conversation", "appointment_id")
    op.create_table(
        "conversation_user",
        sa.Column("conversation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
            name="conversation_user_conversation_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="conversation_user_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "conversation_id", "user_id", name="conversation_user_pkey"
        ),
    )
    # ### end Alembic commands ###
