"""update: fk

Revision ID: 5f79e05cbeb7
Revises: 30d30cac42dc
Create Date: 2024-09-25 15:49:46.238998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f79e05cbeb7'
down_revision: Union[str, None] = '30d30cac42dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'daily_health_check', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_health_check', type_='foreignkey')
    # ### end Alembic commands ###
