"""create table staff

Revision ID: 81a64914a453
Revises: 3f5e9d309b93
Create Date: 2024-10-13 23:38:41.682082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a64914a453'
down_revision: Union[str, None] = '3f5e9d309b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('account_number', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('beneficiary_name', sa.Text(), nullable=True),
    sa.Column('branch_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('idx_staff_email', 'staff', ['email'], unique=False)
    op.create_index('idx_staff_phone_number', 'staff', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_staff_phone_number', table_name='staff')
    op.drop_index('idx_staff_email', table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
