"""remove field for table patient

Revision ID: b03c6e4d2d2b
Revises: d5bdd0e316fa
Create Date: 2024-09-20 17:00:57.227552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03c6e4d2d2b'
down_revision: Union[str, None] = 'd5bdd0e316fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_user_id_fkey', 'patient', type_='foreignkey')
    op.drop_column('patient', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('patient_user_id_fkey', 'patient', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
