"""add field view in table 

Revision ID: bdcfe4ee5e97
Revises: baa76aefad35
Create Date: 2024-10-13 16:12:59.401296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcfe4ee5e97'
down_revision: Union[str, None] = 'baa76aefad35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('view', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'view')
    # ### end Alembic commands ###
