"""rename field

Revision ID: c0567e7490a2
Revises: 9726f3fde895
Create Date: 2024-09-19 17:46:40.666943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0567e7490a2'
down_revision: Union[str, None] = '9726f3fde895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('doctor_manage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient', 'doctor', ['doctor_manage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'doctor_manage_id')
    # ### end Alembic commands ###
