"""remove field name in conversation

Revision ID: c5ac40f0a1ed
Revises: 87beb8979aa6
Create Date: 2024-09-20 16:20:16.759628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ac40f0a1ed'
down_revision: Union[str, None] = '87beb8979aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_name_key', 'conversation', type_='unique')
    op.drop_column('conversation', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('conversation_name_key', 'conversation', ['name'])
    # ### end Alembic commands ###
