"""create table post and comment and add index all talbe

Revision ID: ce4ffed02ba3
Revises: 392e2cb45432
Create Date: 2024-10-13 11:37:34.830930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce4ffed02ba3'
down_revision: Union[str, None] = '392e2cb45432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_author', 'post', ['author_id'], unique=False)
    op.create_index('idx_post_author_title', 'post', ['author_id', 'title'], unique=False)
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_author_post', 'comment', ['author_id', 'post_id'], unique=False)
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_index('ix_comment_post_id', 'comment', ['post_id'], unique=False)
    op.create_index('idx_appoint_name', 'appointment', ['name'], unique=False)
    op.create_index('idx_appointment_status', 'appointment', ['appointment_status'], unique=False)
    op.create_index('idx_conversation_appointment', 'conversation', ['appointment_id'], unique=False)
    op.create_index('idx_conversation_name', 'conversation', ['name'], unique=False)
    op.create_index('idx_daily_health_check_appointment', 'daily_health_check', ['appointment_id'], unique=False)
    op.create_index('idx_daily_health_check_patient', 'daily_health_check', ['patient_id'], unique=False)
    op.create_index('idex_doctor_email', 'doctor', ['email'], unique=False)
    op.create_index('idx_doctor_is_local_person', 'doctor', ['is_local_person'], unique=False)
    op.create_index('ix_doctor_first_name_last_name', 'doctor', ['first_name', 'last_name'], unique=False)
    op.create_index('ix_doctor_phone_number', 'doctor', ['phone_number'], unique=False)
    op.create_index('idx_medical_record_appointment', 'medical_record', ['appointment_id'], unique=False)
    op.create_index('idx_medical_record_doctor_create', 'medical_record', ['doctor_create_id'], unique=False)
    op.create_index('idx_medical_record_doctor_read', 'medical_record', ['doctor_read_id'], unique=False)
    op.create_index('idx_medical_record_patient ', 'medical_record', ['patient_id'], unique=False)
    op.create_index('idx_message_conversation', 'message', ['conversation_id'], unique=False)
    op.create_index('idx_message_reply', 'message', ['reply_id'], unique=False)
    op.create_index('idx_message_sender', 'message', ['sender_id'], unique=False)
    op.create_index('idx_message_sender_conversation', 'message', ['sender_id', 'conversation_id'], unique=False)
    op.create_index('idx_patient_email', 'patient', ['email'], unique=False)
    op.create_index('ix_patient_first_name_last_name', 'patient', ['first_name', 'last_name'], unique=False)
    op.create_index('ix_patient_phone_number', 'patient', ['phone_number'], unique=False)
    op.create_index('ix_rating_doctor', 'rating', ['doctor_id'], unique=False)
    op.create_index('ix_rating_doctor_patient', 'rating', ['doctor_id', 'patient_id'], unique=False)
    op.create_index('idx_user_phone_number', 'user', ['phone_number'], unique=False)
    op.create_index('idx_user_phone_number_password_hash', 'user', ['phone_number', 'password_hash'], unique=False)
    op.create_index('idx_work_schedule_date', 'work_schedule', ['work_date'], unique=False)
    op.create_index('idx_work_schedule_doctor', 'work_schedule', ['doctor_id'], unique=False)
    op.create_index('idx_work_schedule_examination_type', 'work_schedule', ['examination_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_work_schedule_examination_type', table_name='work_schedule')
    op.drop_index('idx_work_schedule_doctor', table_name='work_schedule')
    op.drop_index('idx_work_schedule_date', table_name='work_schedule')
    op.drop_index('idx_user_phone_number_password_hash', table_name='user')
    op.drop_index('idx_user_phone_number', table_name='user')
    op.drop_index('ix_rating_doctor_patient', table_name='rating')
    op.drop_index('ix_rating_doctor', table_name='rating')
    op.drop_index('ix_patient_phone_number', table_name='patient')
    op.drop_index('ix_patient_first_name_last_name', table_name='patient')
    op.drop_index('idx_patient_email', table_name='patient')
    op.drop_index('idx_message_sender_conversation', table_name='message')
    op.drop_index('idx_message_sender', table_name='message')
    op.drop_index('idx_message_reply', table_name='message')
    op.drop_index('idx_message_conversation', table_name='message')
    op.drop_index('idx_medical_record_patient ', table_name='medical_record')
    op.drop_index('idx_medical_record_doctor_read', table_name='medical_record')
    op.drop_index('idx_medical_record_doctor_create', table_name='medical_record')
    op.drop_index('idx_medical_record_appointment', table_name='medical_record')
    op.drop_index('ix_doctor_phone_number', table_name='doctor')
    op.drop_index('ix_doctor_first_name_last_name', table_name='doctor')
    op.drop_index('idx_doctor_is_local_person', table_name='doctor')
    op.drop_index('idex_doctor_email', table_name='doctor')
    op.drop_index('idx_daily_health_check_patient', table_name='daily_health_check')
    op.drop_index('idx_daily_health_check_appointment', table_name='daily_health_check')
    op.drop_index('idx_conversation_name', table_name='conversation')
    op.drop_index('idx_conversation_appointment', table_name='conversation')
    op.drop_index('idx_appointment_status', table_name='appointment')
    op.drop_index('idx_appoint_name', table_name='appointment')
    op.drop_index('ix_comment_post_id', table_name='comment')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_index('ix_comment_author_post', table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_index('idx_post_author_title', table_name='post')
    op.drop_index('idx_post_author', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
