"""updaet link 2 table daily and appointment

Revision ID: cf1b027d1a0f
Revises: db098506417b
Create Date: 2024-09-27 00:28:49.448918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1b027d1a0f'
down_revision: Union[str, None] = 'db098506417b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_health_check', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'daily_health_check', 'appointment', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_health_check', type_='foreignkey')
    op.drop_column('daily_health_check', 'appointment_id')
    # ### end Alembic commands ###
