"""chaneg type datetime to date

Revision ID: db098506417b
Revises: 5f79e05cbeb7
Create Date: 2024-09-25 23:12:35.743271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db098506417b"
down_revision: Union[str, None] = "5f79e05cbeb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_health_check", sa.Column("date_create", sa.Date(), nullable=True)
    )
    op.drop_column("daily_health_check", "time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_health_check",
        sa.Column("time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.drop_column("daily_health_check", "date_create")
    # ### end Alembic commands ###
