from enum import Enum
from typing import Any, Dict, Optional


class ErrorCode(Enum):
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    AUTHEN_FAIL = "AUTHEN_FAIL"
    BAD_REQUEST = "BAD_REQUEST"
    FORBIDDEN = "FORBIDDEN"
    SERVER_ERROR = "SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOW = "METHOD_NOT_ALLOW"
    UNAUTHORIZED = "UNAUTHORIZED"
    CONFLICT = "CONFLICT"
    SIGNATURE_VERIFY_FAIL = "SIGNATURE_VERIFY_FAIL"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    USER_HAVE_BEEN_REGISTERED = "USER_HAVE_BEEN_REGISTERED"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    EMAIL_HAVE_BEEN_REGISTERED = "EMAIL_HAVE_BEEN_REGISTERED"
    LICENSE_NUMBER_HAVE_BEEN_REGISTERED = "LICENSE_NUMBER_HAVE_BEEN_REGISTERED"


CACHE_REFRESH_TOKEN = 60 * 60
CACHE_ACCESS_TOKEN = 60
KEY_CACHE_LOGOUT = "logout"
